<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="54192" started-at="2016-11-21T09:29:25Z" finished-at="2016-11-21T09:30:20Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="54192" started-at="2016-11-21T09:29:25Z" finished-at="2016-11-21T09:30:20Z">
      <class name="beechtreetest.BeechTreeTestSuite">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:beechtreetest.BeechTreeTestSuite@25bbe1b6]" name="beforeTest" is-config="true" duration-ms="708" started-at="2016-11-21T14:29:25Z" finished-at="2016-11-21T14:29:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="BeechTree()[pri:0, instance:beechtreetest.BeechTreeTestSuite@25bbe1b6]" name="BeechTree" duration-ms="53389" started-at="2016-11-21T14:29:26Z" finished-at="2016-11-21T14:30:20Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[bound must be positive]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at beechtreetest.BeechTreeTestSuite.BeechTree(BeechTreeTestSuite.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeechTree -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:beechtreetest.BeechTreeTestSuite@25bbe1b6]" name="afterTest" is-config="true" duration-ms="73" started-at="2016-11-21T14:30:20Z" finished-at="2016-11-21T14:30:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- beechtreetest.BeechTreeTestSuite -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
